### ISSUE TITLE
Rename this repository to events.webmaker.org

### ISSUE THREAD

**Issue by simonwex** [mozilla/events.webmaker.org#240]
* [x] Ensure Travis works
 * [x] Email mofo-eng@
 * [x] Pat back

**Comment by gvn** [comment]
@jbuck Is there something we need to do to get Travis checking PRs again? It doesn't seem like the webhook is working anymore...

**Comment by gvn** [comment]
See #241 for example...

**Comment by jbuck** [comment]
@gvn should be working now

**Comment by gvn** [comment]
@jdotpz Will this renaming affect deployments with Jenkins or any other devops-y stuff?

**Comment by jdotpz** [comment]
Yup!  Was this events-api or events before @gvn ?

**Comment by gvn** [comment]
Just plain 'ol events front end.

**Comment by jdotpz** [comment]
That is now updated, and celebratory measures can now be taken.

**Comment by gvn** [comment]
Huzzah!
